export const ADD_CONVERSATIONS='ADD_CONVERSATIONS';
export const CONVERSATIONS_LOADING='CONVERSATION_LOADING';
export const CONVERSATION_FAILED='CONVERSATIONS_FAILED';

export const SET_ACTIVE_CONVERSATION='SET_ACTIVE_CONVERSATION';
export const ACTIVE_CONVERSATIONS_LOADING='ACTIVE_CONVERSATION_LOADING';
export const ACTIVE_CONVERSATION_FAILED='ACTIVE_CONVERSATIONS_FAILED';
export const DELETE_CONVERSATION='DELETE CONVERSATION';

export const ADD_MESSAGE='ADD_MESSAGE';
export const DELETE_MESSAGE='DELETE_MESSAGE';