export const ADD_CONVERSATIONS='ADD_CONVERSATIONS';
export const CONVERSATIONS_LOADING='CONVERSATION_LOADING';
export const CONVERSATION_FAILED='CONVERSATIONS_FAILED';

export const SET_CONVERSATION='SET_CONVERSATION';
export const DELETE_CONVERSATION='DELETE CONVERSATION';

export const ADD_MESSAGE='ADD_MESSAGE';
export const DELETE_MESSAGE='DELETE_MESSAGE';