export const GET_CONVERSATIONS='GET_CONVERSATIONS';
export const SET_CONVERSATION='SET_CONVERSATION';
export const DELETE_CONVERSATION='DELETE CONVERSATION';

export const ADD_MESSAGE='ADD_MESSAGE';
export const DELETE_MESSAGE='DELETE_MESSAGE';